baseURL = "/"
title   = "Christian Niehoff"
languageCode = "en-us"
theme = "hello-friend-ng"

DefaultContentLanguage = "de"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = true
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[author]
  name = "Christian Niehoff"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage by Christian Niehoff"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = ["images/avatar.jpeg"]

  customCSS = ["custom.css"]

  homeSubtitle = "Infrastructure Engineer"

  contentTypeName = "content"

  # Default theme "light" or "dark"
  defaultTheme = "light"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  gitUrl = "https://github.com/r3kzi/website/commit/"

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .content.

  [params.logo]
    logoText     = "$ cd /home/"
    logoHomeLink = "/"

  [[params.social]]
      name = "github"
      url = "https://github.com/r3kzi"
  [[params.social]]
      name = "twitter"
      url = "https://twitter.com/_rekzi_"
  [[params.social]]
	  name = "linkedin"
	  url = "https://www.linkedin.com/in/christian-niehoff-637b9b17a/"
  [[params.social]]
  	  name = "dockerhub"
  	  url = "https://hub.docker.com/?namespace=rekzi"

[menu]
  [[menu.main]]
    identifier = "about me"
    name       = "~/contact"
    url        = "/about"
  [[menu.main]]
    identifier = "gpgkey"
    name       = "~/gpgkey"
    url        = "/gpgkey"