version: '3'
services:
  hugo:
    image: jojomi/hugo:latest
    container_name: hugo
    volumes:
      - $PWD:/src
      - $PWD/output:/output
    environment:
      - HUGO_THEME=hello-friend-ng
      - HUGO_TYPE=_extended
      - HUGO_WATCH=1
      - HUGO_BASEURL=localhost
    ports:
      - 1313:1313    
