baseurl = "http://christian-niehoff.com" # Hostname (and path) to the root.
title = "Christian Niehoff" # Site title.
theme = "coder" # Set the theme.
languagecode = "en-us" # The site’s language code.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

pluralizelisttitles = false

defaultContentLanguage = "en"

[params] # theme parameters
    author = "Christian Niehoff" # Author's name.
    description = "Christian Niehoff's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
	custom_css = []

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 30
    url  = "/posts/"

[[menu.main]]
    name = "About"
    weight = 99
    url  = "/about"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/rekz1"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/_rekzi"
[[params.social]]
    name = "Keybase"
    icon = "fab fa-keybase"
    weight = 2
    url = "https://keybase.io/cniehoff"

[outputFormats]
    [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"